name: Profile Summary Cards

on:
  schedule:
    - cron: "0 0 * * *" # 毎日 00:00 UTC に実行
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          user: ${{ github.repository_owner }}
          theme: github_dark
